### ISSUE TITLE
Default value should follow a common pattern

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/bifrost#10]
Instead of : 
`if (!postData.timestamp) postData.timestamp = timestamp`
We should : 
postData.timestamp = timestamp || new Date()

The same principle should apply for every field.

**Comment by oleksiireshetnik** [comment]
https://github.com/soixantecircuits/bifrost/commit/bef61e2dfd9104a74471f53796881003d9c7aacc
