### ISSUE TITLE
[nedb-migration-feature] request fails

### ISSUE THREAD

**Issue by Saarg** [soixantecircuits/bifrost#17]
Some post requests that works on the master branch seems to fail on nedb-migration-feature with no error, just `proxy.js - fail - but saved`

the request was made in meteor like this: 

```
request.post({url: url, formData: formData}, function optionalCallback (err, httpResponse, body) {...})
```

**Comment by Saarg** [comment]
in lauchRequest in proxy.js, postData is like this: 

```
files: Array[0]
formData: Object
id: "imageTest"
img: "data:image/png;base64,iVBOR......."
timeStamp: 1470734660373
url: "http://localhost:8000/upload.php"
```

so when it goes through

```
var options = {}

if (!postData.files) {
  options = { form: postData.formData }
}
```

options stays empty and then the request sent is just empty and fails

**Comment by oleksiireshetnik** [comment]
Can you please provide form data content?

**Comment by Saarg** [comment]
069d85c2c453e7238adba1d21791bb12da700827 fixed it
