### ISSUE TITLE
Add reason for saving file for posting later

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/bifrost#5]
The reason why the post failed should be indicate : network issue or remote server error

**Comment by gabrielstuff** [comment]
While Bifrost receive a POST request, it should save the reason why the app is posting to bifrost.
Reason should be a field reason with a string value

**Comment by oleksiireshetnik** [comment]
https://github.com/soixantecircuits/bifrost/commit/34c1118411b3debea266b592ebbef127d786ef4b
