### ISSUE TITLE
Bifrost should implement mdns discovery

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/bifrost#7]
At startup bifrost should declare it's service and broadcast a bifrost service with port information.
This would allow other apps to seamlessly connect to bifrost if needed and post the content to save it

**Comment by oleksiireshetnik** [comment]
https://github.com/soixantecircuits/bifrost/commit/6ed437a8a17f3409dc2bdab9dd486a56f022b5fb

**Comment by gabrielstuff** [comment]
This won't be the case in V2.
