### ISSUE TITLE
Don't handle queue like that

### ISSUE THREAD

**Issue by Art2B** [soixantecircuits/bifrost#8]
The queue must be handled one file at a time and not every file at once. 
On your interval, just take one file, then another :)

**Comment by gabrielstuff** [comment]
The Queue should simply use aync.js : http://caolan.github.io/async/docs.html#.queue

**Comment by oleksiireshetnik** [comment]
https://github.com/soixantecircuits/bifrost/commit/22196578e25101b1002787e0da084e3dbbdebac9
